### ISSUE TITLE
Data not persisting through refreshes

### ISSUE THREAD

**Issue by lukerep** [rocicorp/replicache#1049]
Just got replicache up and running, everything appears to be getting/setting correctly but as soon as I refresh the page nothing is persisted.

Running in NextJS and utilising the `replicache-react` package too.

Can see that data is being written to `IndexedDB` with `rep:<user>` so I'm not sure what is wrong.

Any ideas?

**Comment by aboodman** [comment]
Have you hooked Replicache up to a server yet? It is expected that you will not see data across refreshes without server acknowledgment in Replicache 12. See https://doc.replicache.dev/concepts/offline.

In Replicache 13 (releasing soon) this is fixed. If you are interested you can try the Replicache 13 beta by following the docs here:

https://trunk.doc.replicache.dev/

If the problem is not that the server isn't acknowledging, another cause could be using a different `user` on every page load.

Let me know if either of these help.

**Comment by lukerep** [comment]
No I haven't hooked it up to a server yet, thanks for pointing that out.

I'll have a look at Replicache 13, thanks!
