### ISSUE TITLE
Scan janks the UI thread

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#114]
~~Scan currently pulls in batches of 500~~. This ends up blocking the UI thread for 60ms at a time. We need to improve this, and will. But in the meantime we could change this code to be adaptive -- meaning it should run for 1-2ms and then yield and let other UI stuff happen.

What is the best way to do this kind of work these days? Is it https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API? or requestAnimationFrame?

**Comment by phritz** [comment]
Not clear to me that the best/only way to solve this is at the browser level. I think there might be good reasons to call yeild_now() periodically in our rust code that can run a long time. Not only would it enable the ui to work but it would also enable other queries to work. We don't want one expensive query to severely affect tail latency, ie just because one query has high latency shouldn't cause them all to.

Though not directly applicable, this tokio blog post is relevant: https://tokio.rs/blog/2020-04-preemption

**Comment by aboodman** [comment]
Right on! Didn't think about something like this.

**Comment by arv** [comment]
Not sure what action to take here?

At this point we cannot split work because that would close the IDB transaction (same issue we saw with using a worker)

**Comment by aboodman** [comment]
Does requestIdleCallback relinquish the transaction?

**Comment by aboodman** [comment]
Or requestAnimationFrame?

**Comment by arv** [comment]
Yes to both

The transaction closes after the callback returns. Basically anything that is queued on the message loop closes the tx

**Comment by aboodman** [comment]
I propose that we delay this until prolly trees are implemented. Prolly trees will naturally introduce asynchrony into scan (due to IO to IDB), which might sort of make this a non-issue. It will at least dramatically change the performance characteristics of scan, so maybe we should delay worrying about it until the design we actually want is implemented.
