### ISSUE TITLE
We need to stabilize the perf benchmarks somehow

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#216]
This is close to being useful:

https://replicache-sdk-js-perf-git-perf-data.rocicorp.vercel.app/

... but not useful. See for example the dip in populate perf around 63c44cc24cdeaa40053b533625f3bf0b380ed985. Is it real? If so which commit? Hard to tell.

@phritz it seems like it should not be hard to get this to run on either an dedicated instance in ec2 or at least isolated? I would like to add this to near term work. wdyt?

**Comment by phritz** [comment]
> @phritz it seems like it should not be hard to get this to run on either an dedicated instance in ec2 or at least isolated? I would like to add this to near term work. wdyt?

Definitely seems important to have reliable metrics for the things that matter most, so yes, let's do it.

**Comment by phritz** [comment]
Something we should address: that we dont get fine-grain commit results for repc changes. We should definitely fix this so we don't have to go digging into releases to find when a thing happened. Maybe a smoke perf test on the repc side to guide the search or test-releasing every commit in repc so we can run the benchmarkes on the js side.

**Comment by phritz** [comment]
aaron says:
> OK so @phritz https://github.com/rocicorp/repc/releases/tag/v0.13.0  caused a ~20% reduction in populate perf. 
> ...
> See graphs here: https://replicache-sdk-js-perf-git-perf-data.rocicorp.vercel.app/ and corresponding code here: https://github.com/rocicorp/replicache-sdk-js/blob/master/perf/perf.js#L224
perf/perf.js:224

I went through each commit looking for culprits and this is what I found. My guess is it's this first issue that is causing it:
  - nulls in strings! presumably this text decoder will happily include 0 bytes in strings, as it should: https://github.com/rocicorp/replicache-sdk-js/blob/a1c6693acd6c4bfc7c4505f6f14ce69e378b2525/perf/perf.js#L16. However we disallow nulls in values that we index so it will trigger an info log and not actually be indexed: https://github.com/rocicorp/repc/blob/111ac9d65f95063585a0d804e07866489ec6c171/src/db/write.rs#L238. we also allocate a string in this case: https://github.com/rocicorp/repc/blob/111ac9d65f95063585a0d804e07866489ec6c171/src/db/write.rs#L242 and actually another one deeper down in get_index_keys
  - in change to enable indexing of arrays of strings, when indexing a value for clarity of code we allocate two vectors where previously allocated one: https://github.com/rocicorp/repc/commit/d236be1cfaad55c0503f6096e682e30a9150df71#diff-de56dc115857f21293cddf89faae00fe8e3ea912edc415f23f1460a0759412c4R153
  - we now allocate a log context in put(): https://github.com/rocicorp/repc/commit/d236be1cfaad55c0503f6096e682e30a9150df71#diff-12bae3eeae5df2dd1462fc0318ea11233efb4360f197e65551f0885dd7fd25dfR134
  - we encode our own index key instead of using bytekey, but we do this in the maximally efficient way (reserving enough space up front) so i do not think this is an issue, but mentioning for completeness: https://github.com/rocicorp/repc/commit/19a16986817e8fcbd5b1fbbcf80aaa26d5327677#diff-de56dc115857f21293cddf89faae00fe8e3ea912edc415f23f1460a0759412c4R186

btw careful inferring anything from https://github.com/rocicorp/repc/commit/74db97cabedabb8ae9e6de81c62373b26a8bf474 because there were inefficiencies introduced there eg allocating owned indexkeys instead of using &[]s that were fixed in later commits.

**Comment by arv** [comment]
Closing for now.

We are running the tests on our own EC2 instance which should be more stable.
