### ISSUE TITLE
Perf test IDB

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#312]
We need to know what the maximum performance IDB is capable of on a variety of tasks and platforms so that we can know if it will (alone) meet our goals, or if we need to put something fancier in front of it.

Can we add to our existing perf benchmarks some tests to IDB alone as a baseline? Here are the benchmarks I think we're interested in to start:

* Fastest possible tx throughput
  * Create a tiny (one byte key, one byte value) document in a transaction
* Simulated Replicache mutation
  * Create two 16KB documents
  * Delete two (pre-existing 16KB documents)
  * Update one small key/value pair to contain a different value (simulated set_head call)
* Simulated Replicache read
  * Pre-populate an indexeddb with 10,000 random 16KB documents (160MB of data)
  * Read one of them
* Simulated small Replicache scan
  * Same as above but read 1.6MB of data
  * Read them in parallel, assuming that matters - Replicache will be able to do this typically
* Simulated large Replicache scan
  * Same as above, but read 160MB of data

For each of these benchmarks we want to do any optimization we can think of (e.g., parallel reads) because what we're interested in is: what is the absolute fastest we can achieve on indexeddb.

Also for each of these, we should try with a few different chunk sizes: say 4KB, 8KB, 16KB, so that we can understand the difference.

Finally, @phritz says we should print out not just the throughput like we have been, but also: all the deciles (10/20/30...) With min and max.

**Comment by phritz** [comment]
Nice writeup. I like how we are starting with a design sketch here. 

- i like all the benchmarks you are suggesting! maybe one more: fastest possible large tx throughput where we read or write a single 5MB, 10MB, 100MB, 1GB blob. 

- How much do we care about how realistic the 'simulated replicache' operations are? We should maybe factor in that chunks are going to be stored in something like a BTree, so we are not going to be able to navigate to every chunk with a single read. I'd suggested 32kb chunks and that internal nodes were ~32 bytes (16 for the hash, 10 for the key, several bytes for tags, which is close enough to 32 to just round up). Under those assumptions that's 1k pointer records at the top level. At the very least each dag read results in 2 reads of idbstore, one to get the top level chunk and one to get the appropriate leaf. Assuming 16kb documents that means 16MB accessible in two levels. So if we have more than 16MB of data it's more like 3 serial idb reads to find a chunk's data. But wait, there's more! We also have to read the head to find the top level BTree node. And don't forget that refs are stored separately, so when we read an internal BTree node chunk we are actually doing two serial reads: one for the chunk and one for its refs (we could provide a way to get a chunk w/o its refs I suppose, which would make this part go away). We should also account for writing both the data and its refs in the write, which it looks like happens in parallel. (Should we ignore BTree splits and merges?) So we could maybe break the 'simulated replicache' operations down a little more precisely and explicitly for realism if we wanted. eg
    - first read of a leaf data chunk: read head (1 idb read for data + 1 for refs) + locate leaf (2-3 chunk reads, each of which is 1 idb read for data + 1 for refs) = 6-8 serial reads which if we eliminated automatically reading refs would be 3-4.

- our current benchmarks are going to continue to be misleadingly fast until we have a BTree or something like it under the hood. 

- i do not think we should have a chunk size for ants. A 4KB chunk can only store ~100 32-byte BTree internal node (key, pointer) records, so fanout is not very high. Also if we are talking 16kb values, the *number* of writes we are doing is more likely to affect write performance through variance than their size: smaller chunks means more writes each of which is an opportunity to be slow, whereas there is ~no likely variance in the difference in time to write a 16kb chunk vs a 32kb chunk. So looks to me like we should choose a chunk size that is 32KB or more. (Recall I'm suggesting we write values larger than the target chunk size into a single chunk instead of breaking them up, unless of course we use prolly trees). 

- i want to call attention explicitly to variance as a thing we should pay attention to. We talked about it on slack and aaron suggests here looking at min, max, and the deciles like we talked about so yay. It's a thing I learned at google that even if most operations are fast it might not matter to the user experience because the outliers can ruin the whole thing. So not only do we want to be fast, we also want it to be consistently fast. A primary advantage to doing things in memory is not just speed, but also far less opportunity for variance because there is just a lot less going on on the execution path. I may be preaching to the choir here so sorry for beating this drum again if so, I just did not want to think I was saying something without being sure that it was clear. 

Let me know how I can help.

**Comment by aboodman** [comment]
> How much do we care about how realistic the 'simulated replicache' operations are? 

A lot.

> more like 3 serial idb reads to find a chunk's data
> But wait, there's more!...

These are all good points.

One thing that we found out pretty rapidly on Noms was that typically datastores keep he first two levels of their trees in memory because it's silly to read them over and over.

Perhaps a better way to approach this would be to get the primitives, rather than trying to simulate anything. So like: smallest possible tx, read bandwidth of a single chunk, seeks, read bandwidth of multiple chunks... not sure what else. Then we can estimate what we can achieve from first principles.

> our current benchmarks are going to continue to be misleadingly fast until we have a BTree or something like it under the hood.

It's not clear to me. Right now the benchmarks are reading and writing the entire store over and over...? I get that there will be more seeks, but also I expect that some of those will be cached.

Right now I think our perf is quite below what IDB allows.

> i do not think we should have a chunk size for ants

OK. I am pretty sure that I remember that IDB compresses the data stored implicitly. Our data is going to be very compressible. We need to keep this in mind while designing this and profiling

> i want to call attention explicitly to variance as a thing we should pay attention to.

Agree. Also, Alex Russell tells me that ssd perf on mobile varies greatly with device quality.

**Comment by phritz** [comment]
> Perhaps a better way to approach this would be to get the primitives

Yes, sounds better and like less work. Maybe the primitives we need are:
- unit latency
  - smallest possible (1b) single read, write
  - typical (say, 32kb) json single read, write
  - large json single read, write (1MB, 10MB, 100MB, 1GB)
  - large binary single read, write (1MB, 10MB, 100MB, 1GB)
- bulk throughput
  - 1000 parallel small reads, writes
  - 1000 parallel typical reads, writes
  - 10 parallel large reads, writes (ex-1GB)

> Right now I think our perf is quite below what IDB allows.

I get it, the balance in my mind comes down on the necessity of doing more serial operations with the BTree than we are modeling with the perf test. Of course I can imagine the long road of cache this here and that there, and use this trick to make this other thing fast. But god it would be nice to not have to do all the thinking that that requires every time we see something slow.

**Comment by phritz** [comment]
Recording here because I don't have a better place for it yet. Target for perf:
- with 100MB of data and 100 subscriptions 95% of write-sub-reads of typical size (16-32kb) take <=  3ms
- should work with up to 1G of data

**Comment by aboodman** [comment]
Moved the targets to here: https://github.com/rocicorp/replicache-sdk-js/issues/322

I think we're going to continue to refine these targets as we think about it over the coming weeks.

**Comment by aboodman** [comment]
Fixed by #349
