### ISSUE TITLE
RFE: Expose pending mutations

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#490]
We keep running into use cases to know if a client has any pending mutations.

Some use cases involve:
- If there are no pending mutations it is safe to delete the database and resync from scratch
- Show the user that there are things to upload
- When migrating to a new `schemaVersion` I think we need to wait until all pending mutations have been synced.

The main question is how much to expose?
- A boolean
- The number of pending mutations
- An array of mutation names
- An array of mutation names and args

**Comment by arv** [comment]
This also involves a callback whenever this changes.

**Comment by arv** [comment]
There was already an issue for this (#445) but this one already has more details so closing the other one.

The main motivation in the other one was to know when it is safe to migrate user data. I'll add that to this one.

**Comment by phritz** [comment]
I would hesitate to reveal too much info. Most natural thing that occurs to me is a (server lmid, next local mutation id) or (server lmid, max pending mid) pair that they can use to determine when data are pending and when new data have been received. Simpler, less useful, but impossible to misuse is as you say the number of pending mutations, so that might be best.

Does the caller need any kind of *guarantee* that the system has no pending mutations when they go to do the thing they need to do, or is this more like a hint that now might be a good time to try to do the thing?

**Comment by arv** [comment]
> Does the caller need any kind of _guarantee_ that the system has no pending mutations when they go to do the thing they need to do, or is this more like a hint that now might be a good time to try to do the thing?

I think it depends on the scenario. One possible scenario is that the schema version changed and the developer wants to delete the database and reload the app. In that case a _guarantee_ is important to prevent data loss.

**Comment by arv** [comment]
There are 3 things we want to expose:

```ts

type PendingMutation = {
  readonly name: string;
  readonly id: number;
  readonly args: ReadonlyJSONValue;
};

class Replicache ... { 
  ...
  pendingMutations(): readonly PendingMutation[] {
  readonly lastMutationID: number;
  readonly nextMutationID: number;
}
```

## pendingMutations

Gives a list of mutations that have `mutationID > syncHead.mutationID` that exists on the `main` branch.

## lastMutationID

The mutation ID that was successfully synced to the server.

## nextMutationID

Not sure if this is actually needed? It is the max of the pending plus one

# Open issues?

Should we have an `onPendingChanged` callback?

Then
