### ISSUE TITLE
Use GUID instead of hashes

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#592]
It seems like we do not actually need a hash of the chunk. We never validate the hash on read anyway.

Let's use a GUID instead!

**Comment by tmcw** [comment]
🙌  Support from my side - Hash2 is showing up in profiles, and doing a JSON.stringify of the whole dataset, so the hash can be computed, is also probably less than ideal, too.

**Comment by aboodman** [comment]
I think this is actually likely not necessary or desirable. This was originally my idea, but it conflicts with other changes we are making (#597) where we will need the deduplicating features of hashes. Also I think that the core of the perf issue is completely unrelated (#596).

**Comment by arv** [comment]
Let's not do this.

I opened #605 which should give us a boost

**Comment by aboodman** [comment]
I want to write down here (for next time somebody looks at this) that one reason not to do this is that the mental model that we are all working with is that the data is content-addressed. Even if nothing breaks right *now* if we violate that, it will make the system harder to work in because there will be this edge case in the design space that violates expectations. Let's not do that.
