### ISSUE TITLE
Don't refire subscriptions that haven't changed

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#63]
Minor thing, but it's annoying to developers to re-render for no reason. For a simple thing, we can just keep a hash of the data and only fire if it changes.

Further out we can do pretty fun optimizations to avoid re-executing queries when db hasn't changed in a way that might effect the result.

(My notes on this were written down somewhere but I can't find them -- @arv?)

**Comment by arv** [comment]
It is vaguely mentioned here: https://github.com/rocicorp/replicache/issues/27

**Comment by arv** [comment]
With the current API, the `onData` function gets called with a `ReadTransaction`. This function can then do `get`, `has` and/or `scan`. To determine if the result of `onData` changed we can either;
 - compute a hash of the return value
   - The problem with this is that we cannot reliably compute a hash of an arbitrary js value.
 - keep track of all the accessed keys last time and their hash of their values. 
   - To make this more efficient we should probably compute the hash in Wasm, otherwise we have to `JSON.stringify` (again), copy to an `ArrayBuffer` and then compute the hash using `crypto.subtle.digest`(which is async too)

**Comment by aboodman** [comment]
Hm, ok so summarizing. I'd like to redefine what we're trying to do here, and mechanisms we have considered.

Problem: we fire lots of duplicate subscription change notifications. Right now we fire a change notification whenever the db changes in any way. This causes extra re-renders in apps, which is undeseriable.

Idea #1: Hash the data passed to subscription handlers and check for dupes
- Complication: right now we don't place any restrictions on data returned from subscriptions, so we don't know if it can be serialized
- However, in practice, the intent was to return POD from subscriptions. If we enforce this, then we can compare by hash, but there is a cost to reserialize the data (as JSON) to get its hash.

Idea #2: Keep a hash of all inputs read by transaction
- Keep a running hash of the keys and values read by the transaction as it executes. We could do this in repc, where we have the raw bytes in the first place, so it's a lot cheaper. If the hash changes, refire the transaction.
  - This is a lot more work to impl than idea 1
  - It will fire some dupe transactions (fairly theoretical though)
  - It's still not the ideal solution perf wise (see 3)

Idea #3: 
- The proper solution to this problem is to not re-run subscriptions at all that cannot have changed
- Because we define subscription functions to be pure, we can track which keys (or key ranges) they read and only re-run them in the case where dependent data has changed.
- This is a lot more work to implement - requires design

**Comment by aboodman** [comment]
#2 is tempting. But fleshing out #3 a bit more.

Seems like there are a few parts:
1. We have to record the key ranges to watch somewhere
2. We have to store these subscriptions somewhere
3. We need to test them after each commit
4. We need to notify the bindings

1) can be done either in the bindings or repc.
3) has to be done in repc because it requires access to the old and new data, only repc has that. I believe this implies 2) also has to be in repc.

And easy way to do this would be to expand `openTransaction` to support a 'watch' mode. The result would be that the read transaction would record all read key ranges and create a *subscription* record somewhere internally. When commits happen, we'd compare the changes to these subscription records and notify bindings.

Note this implies a change in how subscriptions are implemented in the bindings. We'd no longer re-run all of them in a single transaction onChange.

**Comment by arv** [comment]
# Design

## Goals

Want to minimize the number of times that a subscribe function is called when the outcome would be the same as last time.

We can achieve this by keeping track of what the subscription depends on (keys and key ranges) and when a mutation changes any of these keys.

### Actors

- **Subscription**: A subscription is an object representing a `Replicache` `subscribe` in JS
  - State:
    - `changed: bool`
    - `keys: Vec<KeyRange>`
      - Used to see if a mutation affects the subscription
    - `id: Id` - Used to associate the JS side subscriptions
  - Operations:
    - `record_get`
    - `record_has`
    - `record_scan`
    - `clear` - when we rerun the subscription we need to clear the keys.
    - `record_mutation` - if the key matches any of the keys we flag the subscription as `changed` and future mutations are no ops.
      - Do we want to keep track of start value to deal with cases where a value goes from `A` to `B` back to `A`?

We need to have multiple subscriptions and the db should probably own these and it is conceptually a `Set` but maybe cleaner/simpler to use a `Map<Id, Subscription>`.

### Code changes

When we create the subscription in JS we call `query` the first time. Instead of using the normal `query` we need to tell repc that we are setting up a subscription and we need to keep track of it. We can probably just add a parameter saying that this is a new subscription (or a subscription without an ID).

Today, when the data changes for any reason we do a single `query` for all the subscription `onData` callbacks. This is not going to work because we might need to update the dependencies on every run of a subscription body.

One option here is for `"commitTransaction"` to return the affected subscriptions (by ID). Then we create a read transaction for each of those and pass in the subscription ID so that the dependencies can be updated as needed.

When we commit a transaction we have all the keys that changed (in `Write.map.pending`). We iterate over all the subscriptions passing in the key to find out if any of the subscriptions have changed. We can then return the IDs of those to JS.

`"removeSubscription"` - We need to add a new RPC to allow removal of a subscription. 

## Open Questions

- Should we always record keys read in a read transaction? If not we need a new impl of `db::Read` or have a boolean flag?
- Should we introduce new RPC names or piggy back on `"openTransaction"`. We need one case for creating a new subscription and one for updating an existing subscription.

**Comment by aboodman** [comment]
> One option here is for "commitTransaction" to return the affected subscriptions (by ID). Then we create a read transaction for each of those and pass in the subscription ID so that the dependencies can be updated as needed.

We can't piggyback on `commitTransaction` because changes can happen other than via the user code executing tx (e.g., sync, other tabs). We could, however, send this data through `onChange`.

> We can probably just add a parameter saying that this is a new subscription

I like that idea. Basically have a bit on `openTransaction` that tells repc that it should subscribe to the keys read by this transaction. Then return (e.g., in `closeTransaction`) the subscription ID. Bindings stash this somewhere and then later on repc tells us a subscription changed by way of `onChange`. Then we just re-run the query and do the same loop again.

A thing that is good about this is that by riding on the transaction processing system we make sure we don't miss any updates. If you imagine a separate `subscribe` rpc, there is the question of update sneaking in between the initial query and the subscription to covered keys.

**Comment by aboodman** [comment]
> When we commit a transaction we have all the keys that changed (in Write.map.pending). We iterate over all the subscriptions passing in the key to find out if any of the subscriptions have changed. We can then return the IDs of those to JS.

This won't work due to multiple tabs! We have to consider how to cause a change that happens in tab A to get subscriptions in tab B to re-fire.

**Comment by phritz** [comment]
- To expand a little bit on what aaron is saying: it doesn't seem like tracking keys that are changing during write is sufficient. There are two other ways changes come in. 

  First is via sync where we currently replace the whole map and/or add/remove/replace specific keys. Seems like we could maybe track such changes during patch with the intent of doing a thing like you describe with write transactions. However here's a question: how do we tell if the key actually changed, like what if we replaced the top level map and then filled the key in with the same value it previously had? Another thing to consider is that another source of changes during sync is replayed commits. Does the subscription get a single notification that a key changed during sync even if it was changed multiple times by multiple replay commits? I assume we only get one notification with the final value. Do we need to determine that the value actually changed though? Like suppose pre-sync the value is X then it gets changed to Y in the sync snapshot, and then a replayed commit changes it to X -- do we get a notification?

  The second source of changes is through a write transaction *or a sync* in another tab. Not clear to me how to handle those...

- Is there any way to piggyback on or utilize what we're doing with indexes? Like the indexes have the same problem: they need to know when keys change. And in some sense a solution to tracking a subscription would be to create an index for it and any time its value hash changes we know to refire.

- What guarantees if any will we make about when the subscription is fired? Like if I have two write txs back to back that change a key we have a subscription for do we want to say anything about when their subscriptions will be fired? In other words, if we have to fire subscriptions do we automatically follow the commit of the write with opening a read tx so the subscription can run, or is it a race with whatever wants to open a tx?

**Comment by aboodman** [comment]
> What guarantees if any will we make about when the subscription is fired?
Like if I have two write txs back to back that change a key we have a
subscription for do we want to say anything about when their subscriptions
will be fired? In other words, if we have to fire subscriptions do we
automatically follow the commit of the write with opening a read tx so the
subscription can run, or is it a race with whatever wants to open a tx?

We *must* ensure that every change to the cache is reflected eventually in
a subscription re-fire. We do *not* need to ensure that every individual
commits gets its own re-fire. We *should not* fire subscriptions
synchronously with commits.

**Comment by aboodman** [comment]
>  is it a race with whatever wants to open a tx?

It seems like for correctness it doesn't matter - they can race. For
performance/quality though, it would be nice to prioritize updating
subscriptions because that is how the UI is going to update after writes.

**Comment by aboodman** [comment]
OK, here is an alternate proposal that I think is the simplest incremental step from where we are today.

# Problem

We have a `subscribe(query, callback)` API that takes an arbitrary js function as `query`, and we promise to invoke `callback` when the results change.

Currently we invoke `callback` too much -- whenever the cache changes for any reason. We would like to tighten this substantially, since typically developers wire it to render functions which are fairly expensive.

# Goal

I think that ideally we should aim to promise that subscriptions are *precise*:

1. `query` will get invoked exactly once whenever a *change* lands on main that modifies one or more keys that were read by the previous invocation of `query`
1. `callback` will get invoked exactly once whenever the result of `query` is different than previous invocation

By *change* I mean either of these two circumstances:

a. A mutation commits in this tab or another tab
a. A sync completes (that is snaps to main) in this tab or another tab
  * Note: we do *not* want to re-run subscriptions until the entire sync completes, including rebase, and snaps to main

# Background

Currently [we write the root hash](https://github.com/rocicorp/replicache-sdk-js/blob/738168fd572d77b32a35bf3105cc40d0bbecd118/src/replicache.ts#L224) of the cache into [LocalStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) whenever we land a change in a tab. We only do this as a way to get the benefit of its side effect - [a notification that fires](https://github.com/rocicorp/replicache-sdk-js/blob/738168fd572d77b32a35bf3105cc40d0bbecd118/src/replicache.ts#L229) in every tab from the same origin.

This is the only web platform API that exists to reliably communicate amongst tabs from same origin other than polling some persistent storage.

Note that this notification has the following properties:
- guaranteed to fire once for every write to a local storage key, regardless of whether the value is different
- event is dispatched asynchronously relative to caller - by the time an event is received, the local storage state can already be different than when it was written
- event carries a reference to the old and new values at time event was generated, regardless of what current state of local storage is at time event is received

See https://html.spec.whatwg.org/multipage/webstorage.html#dom-storage-setitem for details.

# Proposal

Extend the data we write into local storage sufficiently so that subscriptions can be processed within each tab.

# Details

## Watching Subscriptions

When users calls `subscribe(query, callback)` in Replicache, we run `query` and store, associated with that subscription, the *WatchKeySet*, which is a set of *KeyRange*s that the query read.

A *KeyRange* is a pair of *StartKey* and *EndKey* that represent a span of keys that were read, inclusive.

## Calculating Changes

On the writer side, whenever a *Change* happens to the main fork, before the change is committed, we calculate the *ChangeKeySet*, which is a set of *KeyRange*s that were modified.

The *ChangeKeySet* is calculated by doing a diff from old state to new state and gathering unique contiguous spans of keys which were either written or deleted.

### Example

Old State:
```
a: 1
b: 2
c: 3
d: 4
```

New State:
```
a: 10
b: 2
c: 30
```

The *ChangeKeySet* is: `[[a,a],[c,d]]`

## Firing Change Notifications

Once the ChangeKeySet has been computed, the changing tab writes to local storage the new hash along with the ChangeKeySet into a single LocalStorage key.

## Processing Change Notifications

All tabs listen to LocalStorage events, as today. When one is received, for each active subscription, they compare the WatchKeySet to the received ChangeKeySet. If any key ranges overlap, then the subscription is stale and the `query` is re-run.

TODO: We can additionally check if the *results* of the query change by doing `DeepEquals` or computing a hash. We might even want to make this change first, since it is so much simpler.

## Updating Watches

When a `query` is rerun as a result of receiving a change notification, we must again track all the key ranges the new invocation of `query` reads, since its logic might change.

# Problems / Open Issues

* Since local storage events are completely asynchronous it is possible (common?) that a quick series of mutations will generate a series of events, but by the time the first event actually runs, the replicache instance will actually have already been updated to reflect the last event. That is to say, it is not possible to implement goal 1 from above.
** Since we have the root hash in the event is the correct thing to do to simply skip events where the root hash doesn't match current state of cache, assuming that a subsequent event must? 
* How does this interact with indexes? It seems like indexes want same information as the diff that is computed on each change
* Implementation-level sketch. Where is the right place to store this state and implement these algorithms

**Comment by arv** [comment]
> guaranteed to fire once for every write to a local storage key, regardless of whether the value is different

https://html.spec.whatwg.org/multipage/webstorage.html#dom-storage-setitem 3.1:

>  If oldValue is value, then return.

So if we write the same value it will not broadcast. But I do not think we will ever write the same value twice because the root changes.

**Comment by arv** [comment]
> Implementation-level sketch

- The write *ChangeKeySet* is computed in repc. We need to do that in repc for sync anyway. The *ChangeKeySet* is returned in the responses to `maybeEndSync` and `commitTransaction`.
  - The write *ChangeKeySet* for a write transaction could be done either by computing a diff or by registering the keys as they are mutated. For a first pass lets compute a diff since we need to compute the diff anyway for sync.
- The *WatchKeySet* can be computed in either repc or JS. It needs to be stored in JS since repc does not know about subscriptions.
  - I'm leaning towards doing this in repc for consistency and code reuse for future non js sdks

**Comment by aboodman** [comment]
> If oldValue is value, then return.

How did I miss that? Thanks.

**Comment by arv** [comment]
New observation/complication. If we change an index and that index is used in a subscriber we may need to rerun the subscription. I'm not yet sure if there is a way to know not to run the query body?

The subscriber needs to store not only the *WatchKeySet* but also the indexes it uses. Any time we we commit an *indexTransaction* we need to check the subscriptions and rerun the query. If the new *WatchKeySet* is the same we know the result of the query body did not change but we still had to run the query body.

**Comment by aboodman** [comment]
Ah right. Keys in both the WatchKeySet and ChangeKeySet need to be namespaced by their index. And that means that the ChangeKeySet can only be calculated after index updates are applied.

**Comment by aboodman** [comment]
I think no matter what we should do:

> TODO: We can additionally check if the results of the query change by doing DeepEquals or computing a hash. We might even want to make this change first, since it is so much simpler.

As a separate bug, and first. It's an easy quick win we'll want either way. WDYT @arv ?

**Comment by phritz** [comment]
nice writeup, thanks for the context links for people like me :) I have some questions and wish we had a doc for me to drop comments into for a threaded discussion of each. Maybe best if I pose some questions here and we can all jump on a zoom to discuss? a lot of this is going to be you bringing me up to speed on your thinking

- problem statement: is there anything wrong with pushing the problem statement up a level and saying that the app would like to specify ranges of keys that it would like a notification for whenever they change, with the properties you list (precise, etc)? 
- i don't understand the utility of a ChangeKeySet containing ranges of keys that changed, as opposed to simply exactly the set of keys that changed? doing ranges seems like it is an optimization (is it)? if it is i think might be useful to specify that problem separately, because ranges like suggested are not the only way to do it.
- having the subscription query be specified as a function seems indirect to me, what is wrong requiring that they explicitly specify key ranges to subscribe to, eg with a list of ScanOptions? or even more simply, a subscription is specified exactly like a scan? if they want multiple ranges they create multiple subs, and if they want to change subs based on data they are free to do that themselves.
  - as you point out, having query be a function creates the complexity that the query can do different things based on the data it is reading, which necessitates some kind of merging strategy like you suggest. seems like a lot of complexity for gain that i dont understand (but i could believe is worth it if you tell me so).
- presumably the bindings are keeping the set of watched keys?
- I have a suspicion that having both prefix and startkey is going to complexify this. i forget if we think we can implement one in terms of the other, or if we think both are valuable? certainly having both makes index scans more complicated than they would otherwise be.
- "The ChangeKeySet is calculated by doing a diff from old state to new state and gathering unique contiguous spans of keys which were either written or deleted." -- how are we going to do the diff, and how do we determine contiguous spans of keys? 

main thing i want to understand is where a diffless strategy falls down:
  - inside put we already have the new and old value if any  (https://github.com/rocicorp/repc/blob/d0042d987135a2b42acd09ee554a27388d3c387c/src/db/write.rs#L160). they are easy to compare, and we already compute a checksum of both.
  - for a write transaction we could keep a list of changed keys based on this information. we have to be smart about it (eg, changing from "a" to "b" back to "a" is not a change), but that is not a big deal. 
  - when we commit the write we publish this list in local storage along with the new root. if that is too inefficient for some reason (size? speed? how do we know?) that seems like a separate problem to solve. we could compress using spans like suggested, but maybe doing something like huffman encoding the keys would be more efficient, basically replace common prefixes with a shorter substitution string? or.... (i'm sure there are other options)

**Comment by aboodman** [comment]
These are great questions. Let's do this over a zoom sometime soon.

I want to answer one now:

> What is wrong with having the subscription query be specified as a function seems indirect to me, what is wrong requiring that they explicitly specify key ranges to subscribe to, eg with a list of ScanOptions?

This bug was just concerned with how to make the existing API work.

As for why the API is that way. It's basically just a guess as to what API is pleasant to work with. The reasoning goes like this:

- Replicache queries kind of *have* to be functions because the system is transactional. We need some way to specify the bounds of that tx. A function is the obvious way, especially in JS which lacks RAII.
- So subscriptions are just fancy queries that re-run automatically when necessary.

I guess that's a fairly short chain of logic!

**Comment by aboodman** [comment]
(I could totally believe that some other API is better on a variety of axes, this is just what I came up with and why)

**Comment by phritz** [comment]
Notes to self:
- sync: if we tracked the delta using a changelog it would have to span patch and replayed transactions
- in current api bc the query is a function it can use indexes, so you can subscribe to changes within objects and have to do something on index change
- diff and changelog are two different solutions to same problem. rn index updates uses changelog for tx but rebuilds from scratch during sync. if we had either diff we could use it for index updates in addition to subs. (same if we had a more robust changelog)

**Comment by arv** [comment]
> Each call to scan inserts a KeyRange that has the minimum of ScanOptions.prefix and ScanOptions.startKey for the StartKey and the last key read for this scan as the EndKey

I don't think we want to include EndKey. It is not clear what you wanted to use it for? When first reading I thought it would be used to limit the matches to things between start and end but given:

```js
// Value:  {a0: 0}
scan({prefix: 'a'})
// EndKey becomes 'a0'

put('a1', 1}
// Value:  {a0: 0, a1: 1}
```

it should be clear that we cannot use it.

I guess you might have thought it to be useful in combination of `limit` and early returns but as is we always read everything and `limit` gets complicated with add and removes. Better to be safe and rerun the query if the prefix (and start key) match.

**Comment by aboodman** [comment]
Ah. You're right, good catch. I was thinking that the subscriptions are a pure function of the state of the cache, so that means they are a pure function of the state (keys) that they read. Not exactly true.

The purpose of `WatchKeySet` was to be a representation of what the subscription is watching. So it would need to be expanded to correctly handle cases like this.

Maybe there is no more compact representation than literally just storing the details of the calls to `scan()` and `get` that happened.

**Comment by arv** [comment]
> Maybe there is no more compact representation

Maybe. It will be a later optimization

**Comment by aboodman** [comment]
sgtm

**Comment by arv** [comment]
We need to think through the multiple tab case a bit more in detail.

- One thing to keep in mind is that a subscription would never return the wrong result
- The only thing that can potentially happen is that we miss running a subscription

Let's walk through a 2 tab scenario. Lets make some assumptions:
- They are running the same code
- Index definitions are the same. It is possible to delete and add a different index definition but that is a bad idea.

## Scenarios (not going wrong)

### get/has/scan

- Tab A mutates/pulls data that changes keys used in a subscription.
  - Invoke the subscriptions in A
  - We broadcast the new _root hash_ and the _diffs_
- Tab B receives the message
  - Finds the subscriptions for the _diffs_
  - Invoke the subscriptions in B

### index def change

- Tab A creates/deletes an index.
  - Invoke the subscriptions in A
  - We broadcast the _root hash_, empty _diffs_ and the _index name_.
- Tab B receives the message
  - Finds the subscriptions for the _index_name_.
  - Invoke the subscriptions in B
  - At this point subscriptions are going to throw when index was removed... but when recreated they will be run again and hopefully succeed. 

## Scenarios (tab B changes before receiving message)

### get/has/scan

- Tab A mutates/pulls data that changes keys used in a subscription.
  - Invoke the subscriptions in A
  - We broadcast the new _root hash_ and the _diffs_ (_DiffA_)
- Tab B mutates/pulls data that changes keys used in a subscription. 
  - Invoke the subscriptions in B
  - We broadcast the new _root hash_ and the _diffs_ (_DiffB_)
- Tab B receives the message from A
  - Finds the subscriptions for the _diffs_.
  - Invoke the subscriptions in B.  _DiffA_ might be overlap with _DiffB_ or they might be completely disjoint. If they overlap we are going to do extra work. If they are disjoint we are only running the minimal subscriptions.
- Tab A receives the message from B
  - Finds the subscriptions for the _diffs_
  - Invoke the subscriptions in A. At this point we need to do this work because the _DiffB_ is a diff over a newer state than when the subscriptions run.


## Conclusion

We might be doing too much work in a few cases but we are not missing subscriptions.

**Comment by arv** [comment]
I started doing the key ranges and observed the following "issue".

- Have a subscription with a scan with prefix `"b"`.
- Starting with an empty map, change `"a"` and `"c"`, which gives us a changed  key range of `["a", "c"]`.
- Now we need to refire the subscription because we cannot tell if there is any change the affected the scan.

**Comment by arv** [comment]
Closing this. I think it is all covered.

**Comment by aboodman** [comment]
Very cool. 🙌
